Duty-On-Message: '&a%p is now on duty!'
Duty-Off-Message: '&a%p is now off duty!'
Guard-Death-Message: '&4The guard %p has been slain by %k and is now off duty!'
Weapon-Message-Title: '&4The guard %p has requested for your weapon'
Weapon-Message-SubTitle: '&cYou have %t seconds to hand it over!'
Potion-Message-Title: '&4The guard %p has requested for your potions'
Potion-Message-SubTitle: '&cYou have %t seconds to hand it over!'
Title-Time: 5
Guard-Place-Blocks: false
Guard-Brake-Blocks: false
Guard-Only-Commands:
    - 'jail'
    - 'warn'
Blocked-Commands:
    - 'Auc'
    - 'Auction'
    - 'f'
    - 'factions'
Rewards-For-Killing-Guard:
    - 'give %p 1 64'
    - 'give %p 2 64'
Random-Chance-Rewards:
    - '50% give %p 1 1'
    - '15% give %p 1 2'
    - '7% give %p 1 3'
    - '75% give %p 1 4'
Max-Random-Rewards: 2